apimServiceName: ak-prod-apim-cicd
namedValues:
  - name: test-secret
    properties:
      displayName: test-secret
      keyVault:
        identityClientId: 335b813d-d90d-44e6-8b8c-0bbf2e77a616
        secretIdentifier: https://ak-kv-secondary.vault.azure.net/secrets/test-secret/0a1d6c0147d3416283a86e9d797af976
loggers:
diagnostics:
backends:
apis:
