openapi: 3.0.1
info:
  title: ak-test-api01
  description: ''
  version: '1.0'
servers:
  - url: https://ak-dev-apim-cicd.azure-api.net/testapo01
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]